server:
  port: 9095
spring:
  application:
    name: order-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/online_book_store
    username: sipun
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  kafka:
    bootstrap-servers: localhost:8092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer




